import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./style/globals.css";
import Navbar from "@/layout/navbar";
import Footer from "@/layout/footer";

// Setup font Poppins
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // biar bisa variasi font-weight
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Website Kamu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} font-sans bg-gray-900 text-white antialiased`}>
        {/* Navbar muncul di semua halaman */}
        <header className="p-6">
          <Navbar />
        </header>

        {/* Isi halaman */}
        <main className="max-w-7xl mx-auto p-6">{children}</main>
        <footer className="mt-12">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
